-- MySQL Script generated by MySQL Workbench
-- Thu Feb 21 13:21:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema membresia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `membresia` ;

-- -----------------------------------------------------
-- Schema membresia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `membresia` DEFAULT CHARACTER SET utf8 ;
USE `membresia` ;

-- -----------------------------------------------------
-- Table `membresia`.`tipo_adjunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`tipo_adjunto` ;

CREATE TABLE IF NOT EXISTS `membresia`.`tipo_adjunto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `membresia`.`tipo_documento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`departamento` ;

CREATE TABLE IF NOT EXISTS `membresia`.`departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num_departamento` VARCHAR(5) NOT NULL,
  `departamento` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `num_departamento_UNIQUE` (`num_departamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`municipio` ;

CREATE TABLE IF NOT EXISTS `membresia`.`municipio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num_municipio` VARCHAR(5) NOT NULL,
  `departamento_id` INT NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_municipio_departamento1_idx` (`departamento_id` ASC) VISIBLE,
  UNIQUE INDEX `uniqued_mun_depart` (`num_municipio` ASC, `departamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_municipio_departamento1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `membresia`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`tipo_miembro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`tipo_miembro` ;

CREATE TABLE IF NOT EXISTS `membresia`.`tipo_miembro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`tipo_estudio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`tipo_estudio` ;

CREATE TABLE IF NOT EXISTS `membresia`.`tipo_estudio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`estado_civil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`estado_civil` ;

CREATE TABLE IF NOT EXISTS `membresia`.`estado_civil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`miembro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`miembro` ;

CREATE TABLE IF NOT EXISTS `membresia`.`miembro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_miembro` INT NOT NULL,
  `estado_civil` INT NOT NULL,
  `nombres` VARCHAR(150) NOT NULL,
  `apellidos` VARCHAR(150) NOT NULL,
  `tipo_documento` INT NOT NULL,
  `documento` VARCHAR(11) NOT NULL,
  `fecha_naci` DATE NOT NULL,
  `mun_naci` INT NOT NULL,
  `ocupacion_actual` VARCHAR(150) NOT NULL,
  `direccion_corresp` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(10) NULL,
  `celular` VARCHAR(10) NULL,
  `correo` VARCHAR(60) NULL,
  `fecha_bautizo` DATE NOT NULL,
  `mun_bautizo` INT NOT NULL,
  `pastor_bautizo` VARCHAR(150) NOT NULL,
  `fecha_espiritu` DATE NULL,
  `observaciones` VARCHAR(500) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `escolaridad` INT NOT NULL,
  `profesion` VARCHAR(150) NULL,
  `conyuge` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_miembro_tipo_documento1_idx` (`tipo_documento` ASC) VISIBLE,
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC) VISIBLE,
  INDEX `fk_miembro_municipio1_idx` (`mun_naci` ASC) VISIBLE,
  INDEX `fk_miembro_tipo_miembro1_idx` (`tipo_miembro` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  INDEX `fk_miembro_municipio2_idx` (`mun_bautizo` ASC) VISIBLE,
  INDEX `fk_miembro_tipo_estudio1_idx` (`escolaridad` ASC) VISIBLE,
  INDEX `fk_miembro_estado_civil1_idx` (`estado_civil` ASC) VISIBLE,
  CONSTRAINT `fk_miembro_tipo_documento1`
    FOREIGN KEY (`tipo_documento`)
    REFERENCES `membresia`.`tipo_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miembro_municipio1`
    FOREIGN KEY (`mun_naci`)
    REFERENCES `membresia`.`municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miembro_tipo_miembro1`
    FOREIGN KEY (`tipo_miembro`)
    REFERENCES `membresia`.`tipo_miembro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miembro_municipio2`
    FOREIGN KEY (`mun_bautizo`)
    REFERENCES `membresia`.`municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miembro_tipo_estudio1`
    FOREIGN KEY (`escolaridad`)
    REFERENCES `membresia`.`tipo_estudio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miembro_estado_civil1`
    FOREIGN KEY (`estado_civil`)
    REFERENCES `membresia`.`estado_civil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`adjunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`adjunto` ;

CREATE TABLE IF NOT EXISTS `membresia`.`adjunto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_adjunto` INT NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `url` VARCHAR(256) NOT NULL,
  `miembro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adjunto_tipo_adjunto_idx` (`tipo_adjunto` ASC) VISIBLE,
  INDEX `fk_adjunto_miembro1_idx` (`miembro` ASC) VISIBLE,
  CONSTRAINT `fk_adjunto_tipo_adjunto`
    FOREIGN KEY (`tipo_adjunto`)
    REFERENCES `membresia`.`tipo_adjunto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adjunto_miembro1`
    FOREIGN KEY (`miembro`)
    REFERENCES `membresia`.`miembro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`congregacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`congregacion` ;

CREATE TABLE IF NOT EXISTS `membresia`.`congregacion` (
  `id` INT NOT NULL,
  `direccion` VARCHAR(150) NULL,
  `barrio` VARCHAR(100) NULL,
  `telefono` VARCHAR(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`congregacion_miembro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`congregacion_miembro` ;

CREATE TABLE IF NOT EXISTS `membresia`.`congregacion_miembro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `congregacion` INT NOT NULL,
  `miembro` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `fecha_salida` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_congregacion_has_miembro_miembro1_idx` (`miembro` ASC) VISIBLE,
  INDEX `fk_congregacion_has_miembro_congregacion1_idx` (`congregacion` ASC) VISIBLE,
  CONSTRAINT `fk_congregacion_has_miembro_congregacion1`
    FOREIGN KEY (`congregacion`)
    REFERENCES `membresia`.`congregacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_congregacion_has_miembro_miembro1`
    FOREIGN KEY (`miembro`)
    REFERENCES `membresia`.`miembro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`ninios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`ninios` ;

CREATE TABLE IF NOT EXISTS `membresia`.`ninios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `padre` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ninios_miembro1_idx` (`padre` ASC) VISIBLE,
  CONSTRAINT `fk_ninios_miembro1`
    FOREIGN KEY (`padre`)
    REFERENCES `membresia`.`miembro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`cargos` ;

CREATE TABLE IF NOT EXISTS `membresia`.`cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membresia`.`cargos_miembro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membresia`.`cargos_miembro` ;

CREATE TABLE IF NOT EXISTS `membresia`.`cargos_miembro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `miembro` INT NOT NULL,
  `cargo` INT NOT NULL,
  INDEX `fk_miembro_has_cargos_cargos1_idx` (`cargo` ASC) VISIBLE,
  INDEX `fk_miembro_has_cargos_miembro1_idx` (`miembro` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_miembro_has_cargos_miembro1`
    FOREIGN KEY (`miembro`)
    REFERENCES `membresia`.`miembro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miembro_has_cargos_cargos1`
    FOREIGN KEY (`cargo`)
    REFERENCES `membresia`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `membresia`.`tipo_adjunto`
-- -----------------------------------------------------
START TRANSACTION;
USE `membresia`;
INSERT INTO `membresia`.`tipo_adjunto` (`id`, `name`) VALUES (1, 'Concepto Divorcio');
INSERT INTO `membresia`.`tipo_adjunto` (`id`, `name`) VALUES (2, 'Foto');
INSERT INTO `membresia`.`tipo_adjunto` (`id`, `name`) VALUES (3, 'Firma');
INSERT INTO `membresia`.`tipo_adjunto` (`id`, `name`) VALUES (4, 'Acta defuncion');
INSERT INTO `membresia`.`tipo_adjunto` (`id`, `name`) VALUES (5, 'Documento Identidad');
INSERT INTO `membresia`.`tipo_adjunto` (`id`, `name`) VALUES (6, 'Registro civil');

COMMIT;


-- -----------------------------------------------------
-- Data for table `membresia`.`tipo_documento`
-- -----------------------------------------------------
START TRANSACTION;
USE `membresia`;
INSERT INTO `membresia`.`tipo_documento` (`id`, `name`) VALUES (1, 'Cedula de Ciudadania');
INSERT INTO `membresia`.`tipo_documento` (`id`, `name`) VALUES (2, 'Tarjeta de identidad');
INSERT INTO `membresia`.`tipo_documento` (`id`, `name`) VALUES (3, 'Cedula extranjeria');
INSERT INTO `membresia`.`tipo_documento` (`id`, `name`) VALUES (4, 'Pasaporte');

COMMIT;


-- -----------------------------------------------------
-- Data for table `membresia`.`tipo_miembro`
-- -----------------------------------------------------
START TRANSACTION;
USE `membresia`;
INSERT INTO `membresia`.`tipo_miembro` (`id`, `name`) VALUES (1, 'Creyente');
INSERT INTO `membresia`.`tipo_miembro` (`id`, `name`) VALUES (2, 'Pastor');

COMMIT;


-- -----------------------------------------------------
-- Data for table `membresia`.`estado_civil`
-- -----------------------------------------------------
START TRANSACTION;
USE `membresia`;
INSERT INTO `membresia`.`estado_civil` (`id`, `name`) VALUES (1, 'Soltero(a)');
INSERT INTO `membresia`.`estado_civil` (`id`, `name`) VALUES (2, 'Casado(a) por notaria');
INSERT INTO `membresia`.`estado_civil` (`id`, `name`) VALUES (3, 'Casado(a) por IPUC');
INSERT INTO `membresia`.`estado_civil` (`id`, `name`) VALUES (4, 'Divorciado(a)');
INSERT INTO `membresia`.`estado_civil` (`id`, `name`) VALUES (5, 'Viudo(a)');

COMMIT;


-- -----------------------------------------------------
-- Data for table `membresia`.`cargos`
-- -----------------------------------------------------
START TRANSACTION;
USE `membresia`;
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (1, 'Diacono secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (2, 'Diacono tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (3, 'Diacono auxiliar');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (4, 'Jovenes Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (5, 'Jovenes Sub lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (6, 'Jovenes Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (7, 'Jovenes Tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (8, 'Jovenes Auxiliar');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (9, 'Damas Dorcas Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (10, 'Damas Dorcas Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (11, 'Damas Dorcas Tesorera');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (12, 'Damas Dorcas Secretaria');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (13, 'Damas Dorcas Auxiliar');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (14, 'Escuela Dominical Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (15, 'Escuela Dominical Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (16, 'Escuela Dominical Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (17, 'Escuela Dominical Tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (18, 'Escuela Dominical Auxiliar');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (19, 'Escuela Dominical Maestro');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (20, 'Misiones Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (21, 'Misiones Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (22, 'Misiones Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (23, 'Misiones Tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (24, 'Misiones Auxiliar');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (25, 'Refam Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (26, 'Refam Acompanante');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (27, 'Caballeros Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (28, 'Caballeros Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (29, 'Caballeros Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (30, 'Caballeros Tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (31, 'Caballeros Auxiliar');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (32, 'Decom Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (33, 'Decom Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (34, 'Decom Tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (35, 'Decom Auxiliar ');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (36, 'Decom Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (37, 'Musica Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (38, 'Musica Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (39, 'Musica Tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (40, 'Musica Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (41, 'Musica Auxiliar');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (42, 'Musica Integrante');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (43, 'Artistica Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (44, 'Artistica Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (45, 'Artistica Tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (46, 'Artistica Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (47, 'Artistica Auxiliar ');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (48, 'Artistica Integrante');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (49, 'Eclesial Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (50, 'Eclesial Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (51, 'Eclesial Tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (52, 'Eclesial Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (53, 'Eclesial Auxiliar ');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (54, 'Eclesial Integrante');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (55, 'Aseo Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (56, 'Aseo Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (57, 'Aseo Tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (58, 'Aseo Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (59, 'Aseo Integrante ');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (60, 'Ujier Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (61, 'Ujier Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (62, 'Ujier Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (63, 'Ujier Tesorero ');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (64, 'Ujier Integrante');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (65, 'Ujier Auxiliar ');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (66, 'Mision Juvenil Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (67, 'Mision juvenil Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (68, 'Mision Juvenil Tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (69, 'Mision Juvenil Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (70, 'Mision Juvenil Auxiliar ');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (71, 'Mision Juvenil Integrante');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (72, 'Bernabe Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (73, 'Bernabe Sub Lider');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (74, 'Bernabe Tesorero');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (75, 'Bernabe Secretario');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (76, 'Bernabe Auxiliar');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (77, 'Bernabe Integrante');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (78, 'Cordinador Recursos Educativos');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (79, 'Cordinador Educacion Cristiana');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (80, 'Cordinador Musica');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (81, 'Cordinador Artistica');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (82, 'Cordinador Educacion Secular');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (83, 'Cordinador Educacion Teologica');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (84, 'Cordinador Misiones');
INSERT INTO `membresia`.`cargos` (`id`, `name`) VALUES (85, 'Cordinador Refam');

COMMIT;

